In [1]:
"""
https://www.jianshu.com/p/d678c5e44a6b
torch常用基础函数    
"""
import torch
import torch.nn.functional as F     # 激励函数都在这
from torch.autograd import Variable
import numpy as np
# python 的可视化模块, 我有教程 (https://morvanzhou.github.io/tutorials/data-manipulation/plt/)
import matplotlib.pyplot as plt
%matplotlib inline

**1.张量Tensors**

In [2]:
x = torch.rand(5,3)
x

tensor([[0.3023, 0.1208, 0.1272],
        [0.1766, 0.5085, 0.8517],
        [0.5513, 0.9506, 0.6067],
        [0.8191, 0.4089, 0.0038],
        [0.6152, 0.8712, 0.9641]])

In [3]:
# 如果obj是一个pytorch张量，则返回True
torch.is_tensor(x)

True

In [4]:
# 如果obj是一个pytorch storage对象，则返回True
torch.is_storage(x)

False

In [5]:
# 返回input张量中的元素个数
torch.numel(x)

15

**2. 创建操作**

In [6]:
"""
torch.eye(n, m=None, out=None):
返回一个2维张量，对角线为1,其它位置为0

n (int) -行数
m (int, optional)列数，如果为None,则默认为n
out (Tensor, optional)
"""
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [7]:
nda = np.array([[1, 2], [3, 4]])
print(type(nda))
nda

<class 'numpy.ndarray'>


array([[1, 2],
       [3, 4]])

In [8]:
nda_tr = torch.from_numpy(nda)
nda_tr

tensor([[1, 2],
        [3, 4]])

In [9]:
"""
将numpy.ndarray转换为Tensor，返回的张量tensor和numpy的ndarray共享同一内存空间，
修改一个会导致另一个也被修改，返回的张量不能改变大小
"""

'\n将numpy.ndarray转换为Tensor，返回的张量tensor和numpy的ndarray共享同一内存空间，\n修改一个会导致另一个也被修改，返回的张量不能改变大小\n'

In [10]:
nda[0,1]=9
nda

array([[1, 9],
       [3, 4]])

In [11]:
nda_tr

tensor([[1, 9],
        [3, 4]])

In [12]:
"""
torch.linspace(start, end, steps=100, out=None):
返回一个1维张量，包含在start和end上均匀间隔的steps个点

start (float) -序列起点
end (float) - 序列终点
steps (int) - 在start与end间生成的样本数
out (Tensor, optional) - 结果张量
"""

'\ntorch.linspace(start, end, steps=100, out=None):\n返回一个1维张量，包含在start和end上均匀间隔的steps个点\n\nstart (float) -序列起点\nend (float) - 序列终点\nsteps (int) - 在start与end间生成的样本数\nout (Tensor, optional) - 结果张量\n'

In [13]:
torch.linspace(1, 100, steps=10,out=None)

tensor([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [14]:
"""
torch.logspace(start, end, steps=100, out=None):
返回一个1维张量，包含在区间10exp(start)和10exp(end)上以对数刻度均匀间隔的 steps个点。
"""

'\ntorch.logspace(start, end, steps=100, out=None):\n返回一个1维张量，包含在区间10exp(start)和10exp(end)上以对数刻度均匀间隔的 steps个点。\n'

## WWY start here

In [15]:
torch.logspace(0, 10, steps=6,out=None)

tensor([1.0000e+00, 1.0000e+02, 1.0000e+04, 1.0000e+06, 1.0000e+08, 1.0000e+10])

In [16]:
'''
torch.ones(*sizes, out=None):
返回一个全为1的张量，形状由可变参数sizes定义

sizes (int...) - 整数序列，定义了输出形状
'''

'\ntorch.ones(*sizes, out=None):\n返回一个全为1的张量，形状由可变参数sizes定义\n\nsizes (int...) - 整数序列，定义了输出形状\n'

In [17]:
torch.ones(2,4, out=None)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
'''
torch.rand(*sizes, out=None):
返回一个张量，包含了从区间(0, 1)的均匀分布中抽取的一组随机数，形状由可变参数sizes定义。
'''

'\ntorch.rand(*sizes, out=None):\n返回一个张量，包含了从区间(0, 1)的均匀分布中抽取的一组随机数，形状由可变参数sizes定义。\n'

In [19]:
torch.rand(3,5)

tensor([[0.9248, 0.0830, 0.6693, 0.6845, 0.8389],
        [0.5217, 0.4494, 0.5006, 0.4137, 0.5997],
        [0.4796, 0.6178, 0.9578, 0.1058, 0.3239]])

In [20]:
'''
torch.randn(*sizes, out=None):
返回一个张量，包含了从标准正态分布(mean=0, std=1)中抽取一组随机数，形状由可变参数sizes定义。
'''

'\ntorch.randn(*sizes, out=None):\n返回一个张量，包含了从标准正态分布(mean=0, std=1)中抽取一组随机数，形状由可变参数sizes定义。\n'

In [21]:
torch.randn(3,4)

tensor([[ 0.2397,  0.6845,  0.7244, -1.8536],
        [-0.0914, -0.2976,  1.0421, -0.9732],
        [ 2.1047,  0.0220,  1.3665, -0.6199]])

In [22]:
'''
torch.randperm(n, out=None):
给定参数n，返回一个从0到n-1的随机整数排列

n (int) - 上边界(不包含）
'''

'\ntorch.randperm(n, out=None):\n给定参数n，返回一个从0到n-1的随机整数排列\n\nn (int) - 上边界(不包含）\n'

In [23]:
torch.randperm(5)

tensor([3, 0, 2, 1, 4])

In [24]:
'''
torch.arange(start, end, step=1, out=None):
返回一个1维张量，长度为floor((end-start)/step)，以step`为步长的一组序列值。

start (float) - 起点
end (float) - 终点(不包含）
step (float) - 相邻点的间隔大小
out (Tensor, optional)
'''

'\ntorch.arange(start, end, step=1, out=None):\n返回一个1维张量，长度为floor((end-start)/step)，以step`为步长的一组序列值。\n\nstart (float) - 起点\nend (float) - 终点(不包含）\nstep (float) - 相邻点的间隔大小\nout (Tensor, optional)\n'

In [25]:
torch.arange(1, 10, step=3, out=None)

tensor([1, 4, 7])

In [26]:
torch.range(1, 10, step=3, out=None)
# 推荐使用torch.arange()

//anaconda3/envs/spinningup/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  """Entry point for launching an IPython kernel.


tensor([ 1.,  4.,  7., 10.])

In [27]:
'''
torch.zeros(*sizes, out=None):
返回一个全为标量0的张量，形状由可变参数sizes定义
'''

'\ntorch.zeros(*sizes, out=None):\n返回一个全为标量0的张量，形状由可变参数sizes定义\n'

In [28]:
torch.zeros(3,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

**3. 索引，切片，连接，换位(Index, Slicing, Joining, Mutating)**

In [29]:
'''
torch.cat(inputs, dimension=0):
在给定维度上对输入的张量序列seq进行连接操作。

inputs (sequence of Tensors)
dimension (int optional) - 沿着此维连接张量序列
'''

'\ntorch.cat(inputs, dimension=0):\n在给定维度上对输入的张量序列seq进行连接操作。\n\ninputs (sequence of Tensors)\ndimension (int optional) - 沿着此维连接张量序列\n'

In [30]:
x

tensor([[0.3023, 0.1208, 0.1272],
        [0.1766, 0.5085, 0.8517],
        [0.5513, 0.9506, 0.6067],
        [0.8191, 0.4089, 0.0038],
        [0.6152, 0.8712, 0.9641]])

In [31]:
torch.cat((x, x, x), 1)

tensor([[0.3023, 0.1208, 0.1272, 0.3023, 0.1208, 0.1272, 0.3023, 0.1208, 0.1272],
        [0.1766, 0.5085, 0.8517, 0.1766, 0.5085, 0.8517, 0.1766, 0.5085, 0.8517],
        [0.5513, 0.9506, 0.6067, 0.5513, 0.9506, 0.6067, 0.5513, 0.9506, 0.6067],
        [0.8191, 0.4089, 0.0038, 0.8191, 0.4089, 0.0038, 0.8191, 0.4089, 0.0038],
        [0.6152, 0.8712, 0.9641, 0.6152, 0.8712, 0.9641, 0.6152, 0.8712, 0.9641]])

In [32]:
'''
torch.chunk(tensor, chunks, dim=0):
在给定维度上将输入张量进行分块

tensors(Tensors) - 待分场的输入张量
chunks (int) - 分块的个数
dim (int) - 沿着此维度
'''

'\ntorch.chunk(tensor, chunks, dim=0):\n在给定维度上将输入张量进行分块\n\ntensors(Tensors) - 待分场的输入张量\nchunks (int) - 分块的个数\ndim (int) - 沿着此维度\n'

In [33]:
torch.chunk(x, 2, 1)

(tensor([[0.3023, 0.1208],
         [0.1766, 0.5085],
         [0.5513, 0.9506],
         [0.8191, 0.4089],
         [0.6152, 0.8712]]),
 tensor([[0.1272],
         [0.8517],
         [0.6067],
         [0.0038],
         [0.9641]]))

In [34]:
'''
torch.gather(input, dim, index, out=None):
沿给定轴dim,将输入索引张量index指定位置的值进行聚合。

input(Tensor) - 源张量
dim(int) - 索引的轴
index(LongTensor) - 聚合元素的下标
out - 目标张量
'''

'\ntorch.gather(input, dim, index, out=None):\n沿给定轴dim,将输入索引张量index指定位置的值进行聚合。\n\ninput(Tensor) - 源张量\ndim(int) - 索引的轴\nindex(LongTensor) - 聚合元素的下标\nout - 目标张量\n'

In [35]:
torch.gather(x, 1, torch.LongTensor([[0,1],[1,1],[2,2],[0,0],[2,1]]))

tensor([[0.3023, 0.1208],
        [0.5085, 0.5085],
        [0.6067, 0.6067],
        [0.8191, 0.8191],
        [0.9641, 0.8712]])

In [36]:
'''
torch.index_select(input, dim, index, out=None):
沿指定维度对输入进行切片，取index中指定的相应项，然后返回一个新的张量，返回的张量与原始张量有相同的维度(在指定轴上)，返回的张量与原始张量不共享内存空间

input(Tensor) - 输入张量
dim(int) - 索引的轴
index(LongTensor) - 包含索引下标的一维张量
out - 目标张量
'''

'\ntorch.index_select(input, dim, index, out=None):\n沿指定维度对输入进行切片，取index中指定的相应项，然后返回一个新的张量，返回的张量与原始张量有相同的维度(在指定轴上)，返回的张量与原始张量不共享内存空间\n\ninput(Tensor) - 输入张量\ndim(int) - 索引的轴\nindex(LongTensor) - 包含索引下标的一维张量\nout - 目标张量\n'

In [37]:
torch.index_select(x, 0, torch.tensor([0,2]))

tensor([[0.3023, 0.1208, 0.1272],
        [0.5513, 0.9506, 0.6067]])

In [38]:
'''
torch.masked_select(input, mask, out=None):
根据掩码张量mask中的二元值，取输入张量中的指定项，将取值返回到一个新的1D张量。
张量mask须跟input张量有相同的元素数目，但形状或维度不需要相同。返回的张量不与原始张量共享内存空间

input(Tensor) - 输入张量
mask(ByteTensor) - 掩码张量，包含了二元索引值
out - 目标张量
'''

'\ntorch.masked_select(input, mask, out=None):\n根据掩码张量mask中的二元值，取输入张量中的指定项，将取值返回到一个新的1D张量。\n张量mask须跟input张量有相同的元素数目，但形状或维度不需要相同。返回的张量不与原始张量共享内存空间\n\ninput(Tensor) - 输入张量\nmask(ByteTensor) - 掩码张量，包含了二元索引值\nout - 目标张量\n'

In [39]:
mask = torch.ByteTensor([[1,1,0],[1,1,0],[1,1,0], [0,0,1], [1,0,1]])
torch.masked_select(x, mask)

/Users/distiller/project/conda/conda-bld/pytorch_1579022036889/work/aten/src/ATen/native/LegacyDefinitions.cpp:70: UserWarning: masked_select received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.


tensor([0.3023, 0.1208, 0.1766, 0.5085, 0.5513, 0.9506, 0.0038, 0.6152, 0.9641])

In [40]:
'''
torch.nonzero(input, out=None):
返回一个包含输入input中非零元素索引的张量，输出张量中的每行包含输入中非零元素的索引
若输入input有n维，则输出的索引张量output形状为z * n, 这里z是输入张量input中所有非零元素的个数

input(Tensor) - 输入张量
out - 包含索引值的结果张量
'''

'\ntorch.nonzero(input, out=None):\n返回一个包含输入input中非零元素索引的张量，输出张量中的每行包含输入中非零元素的索引\n若输入input有n维，则输出的索引张量output形状为z * n, 这里z是输入张量input中所有非零元素的个数\n\ninput(Tensor) - 输入张量\nout - 包含索引值的结果张量\n'

In [41]:
torch.nonzero(x)

tensor([[0, 0],
        [0, 1],
        [0, 2],
        [1, 0],
        [1, 1],
        [1, 2],
        [2, 0],
        [2, 1],
        [2, 2],
        [3, 0],
        [3, 1],
        [3, 2],
        [4, 0],
        [4, 1],
        [4, 2]])

In [42]:
'''
torch.split(tensor, split_size, dim=0):
将输入张量分割成相等形状的chunks(如果可分)。如果沿指定维的张量形状大小不能被split_size整分，则最后一个分块会小于其它分块。

tensor(Tensor) - 待分割张量
split_size(int) - 单个分块的形状大小
dim(int) - 沿着此维进行分割
'''

'\ntorch.split(tensor, split_size, dim=0):\n将输入张量分割成相等形状的chunks(如果可分)。如果沿指定维的张量形状大小不能被split_size整分，则最后一个分块会小于其它分块。\n\ntensor(Tensor) - 待分割张量\nsplit_size(int) - 单个分块的形状大小\ndim(int) - 沿着此维进行分割\n'

In [43]:
torch.split(x, 3, 0)

(tensor([[0.3023, 0.1208, 0.1272],
         [0.1766, 0.5085, 0.8517],
         [0.5513, 0.9506, 0.6067]]),
 tensor([[0.8191, 0.4089, 0.0038],
         [0.6152, 0.8712, 0.9641]]))

In [44]:
'''
torch.squeeze(input, dim=None, out=None):
将输入张量形状中的1去除并返回，如果输入是形如(A * 1 * B * 1 * C * 1 *D)，那么输出形状就为：(A * B * C * D)。
当给定dim时，则只在给定维度上进行挤压，如输入形状为(A * 1 * B)，squeeze(input, 0)，将会保持张量不变，只有用squeeze(input, 1)，形状会变成(A *B)。
输入张量与返回张量共享内存

input(Tensor) - 输入张量
dim(int, optional) - 如果给定，则只在给定维度挤压
out(Tensor, optional) - 输出张量
'''

'\ntorch.squeeze(input, dim=None, out=None):\n将输入张量形状中的1去除并返回，如果输入是形如(A * 1 * B * 1 * C * 1 *D)，那么输出形状就为：(A * B * C * D)。\n当给定dim时，则只在给定维度上进行挤压，如输入形状为(A * 1 * B)，squeeze(input, 0)，将会保持张量不变，只有用squeeze(input, 1)，形状会变成(A *B)。\n输入张量与返回张量共享内存\n\ninput(Tensor) - 输入张量\ndim(int, optional) - 如果给定，则只在给定维度挤压\nout(Tensor, optional) - 输出张量\n'

In [45]:
y = torch.zeros(2, 1, 2, 1, 2)
torch.squeeze(y)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [46]:
'''
torch.stack(sequence, dim=0):
沿着一个新维度对输入张量进行连接，序列中所有张量都应该为相同的形状。

sequence(Sequence) - 待连接的张量序列
dim(int) - 插入的维度
'''

'\ntorch.stack(sequence, dim=0):\n沿着一个新维度对输入张量进行连接，序列中所有张量都应该为相同的形状。\n\nsequence(Sequence) - 待连接的张量序列\ndim(int) - 插入的维度\n'

In [47]:
y = torch.zeros(5,3)
z = torch.ones(5,3)
torch.stack([x, y, z], dim=1)

tensor([[[0.3023, 0.1208, 0.1272],
         [0.0000, 0.0000, 0.0000],
         [1.0000, 1.0000, 1.0000]],

        [[0.1766, 0.5085, 0.8517],
         [0.0000, 0.0000, 0.0000],
         [1.0000, 1.0000, 1.0000]],

        [[0.5513, 0.9506, 0.6067],
         [0.0000, 0.0000, 0.0000],
         [1.0000, 1.0000, 1.0000]],

        [[0.8191, 0.4089, 0.0038],
         [0.0000, 0.0000, 0.0000],
         [1.0000, 1.0000, 1.0000]],

        [[0.6152, 0.8712, 0.9641],
         [0.0000, 0.0000, 0.0000],
         [1.0000, 1.0000, 1.0000]]])

In [48]:
'''
torch.t(input, out=None):
输入一个矩阵(2维张量)，并转置0,1维，可以被视为transpose(input, 0, 1)的简写函数

input(Tensor) - 输入张量
out(Tensor, optional) - 结果张量
'''

'\ntorch.t(input, out=None):\n输入一个矩阵(2维张量)，并转置0,1维，可以被视为transpose(input, 0, 1)的简写函数\n\ninput(Tensor) - 输入张量\nout(Tensor, optional) - 结果张量\n'

In [49]:
torch.t(x)

tensor([[0.3023, 0.1766, 0.5513, 0.8191, 0.6152],
        [0.1208, 0.5085, 0.9506, 0.4089, 0.8712],
        [0.1272, 0.8517, 0.6067, 0.0038, 0.9641]])

In [50]:
'''
torch.transpose(input, dim0, dim1, out=None):
返回输入矩阵input的转置，交换维度dim0和dim1。输入张量与输出张量共享内存。

input(Tensor) - 输入张量
dim0(int) - 转置的第一维
dim1(int) - 转置的第二维
'''

'\ntorch.transpose(input, dim0, dim1, out=None):\n返回输入矩阵input的转置，交换维度dim0和dim1。输入张量与输出张量共享内存。\n\ninput(Tensor) - 输入张量\ndim0(int) - 转置的第一维\ndim1(int) - 转置的第二维\n'

In [51]:
torch.transpose(x, 0, 1)

tensor([[0.3023, 0.1766, 0.5513, 0.8191, 0.6152],
        [0.1208, 0.5085, 0.9506, 0.4089, 0.8712],
        [0.1272, 0.8517, 0.6067, 0.0038, 0.9641]])

In [52]:
'''
torch.unbind(tensor, dim=0)[source]:
移除指定维度后，返回一个元组，包含了沿着指定维切片后的各个切片

tensor(Tensor) - 输入张量
dim(int) - 删除的维度
'''

'\ntorch.unbind(tensor, dim=0)[source]:\n移除指定维度后，返回一个元组，包含了沿着指定维切片后的各个切片\n\ntensor(Tensor) - 输入张量\ndim(int) - 删除的维度\n'

In [53]:
torch.unbind(x, 1)

(tensor([0.3023, 0.1766, 0.5513, 0.8191, 0.6152]),
 tensor([0.1208, 0.5085, 0.9506, 0.4089, 0.8712]),
 tensor([0.1272, 0.8517, 0.6067, 0.0038, 0.9641]))

In [54]:
'''
torch.unsqueeze(input, dim, out=None):
返回一个新的张量，对输入的指定位置插入维度1，返回张量与输入张量共享内存，若dim为负，则将被转化为dim+input.dim()+1

tensor(Tensor) - 输入张量
dim(int) - 插入维度的索引
out(Tensor, optional) - 结果张量
'''

'\ntorch.unsqueeze(input, dim, out=None):\n返回一个新的张量，对输入的指定位置插入维度1，返回张量与输入张量共享内存，若dim为负，则将被转化为dim+input.dim()+1\n\ntensor(Tensor) - 输入张量\ndim(int) - 插入维度的索引\nout(Tensor, optional) - 结果张量\n'

In [55]:
torch.unsqueeze(x, 1)

tensor([[[0.3023, 0.1208, 0.1272]],

        [[0.1766, 0.5085, 0.8517]],

        [[0.5513, 0.9506, 0.6067]],

        [[0.8191, 0.4089, 0.0038]],

        [[0.6152, 0.8712, 0.9641]]])

**4. 随机抽样Random sampling**

In [56]:
'''
torch.manual_seed(seed)
设定生成随机数的种子，并返回一个torch._C.Generator对象
参数: seed (int or long) – 种子
'''

'\ntorch.manual_seed(seed)\n设定生成随机数的种子，并返回一个torch._C.Generator对象\n参数: seed (int or long) – 种子\n'

In [57]:
torch.manual_seed(3)

In [58]:
#返回生成随机数的原始种子值（python long）

torch.initial_seed()

3

In [59]:
'''
torch.get_rng_state()[source]
返回随机生成器状态(ByteTensor)
'''

'\ntorch.get_rng_state()[source]\n返回随机生成器状态(ByteTensor)\n'

In [60]:
rng_state = torch.get_rng_state()
rng_state

tensor([3, 0, 0,  ..., 0, 0, 0], dtype=torch.uint8)

In [61]:
'''
torch.set_rng_state(new_state)[source]:
设定随机生成器状态参数：new_state(torch.ByteTensor) - 期望的状态
'''

'\ntorch.set_rng_state(new_state)[source]:\n设定随机生成器状态参数：new_state(torch.ByteTensor) - 期望的状态\n'

In [62]:
torch.set_rng_state(rng_state)

In [63]:
torch.default_generator

In [64]:
'''
torch.bernoulli(input, out=None):
从伯努利分布中抽取二元随机数(0或者1），输入中所有值必须在[0, 1]区间，输出张量的第i个元素值，将以输入张量的第i个概率值等于1。
返回值将会是与输入相同大小的张量，每个值为0或1

input(Tensor) - 输入为伯努利分布的概率值(probability of drawing "1")
out(Tensor, optional)
'''

'\ntorch.bernoulli(input, out=None):\n从伯努利分布中抽取二元随机数(0或者1），输入中所有值必须在[0, 1]区间，输出张量的第i个元素值，将以输入张量的第i个概率值等于1。\n返回值将会是与输入相同大小的张量，每个值为0或1\n\ninput(Tensor) - 输入为伯努利分布的概率值(probability of drawing "1")\nout(Tensor, optional)\n'

In [65]:
a = torch.zeros(3,5)
torch.bernoulli(a)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [66]:
'''
torch.multinomial(input, num_samples, replacement=False, out=None):
返回一个张量，每行包含从input相应行中定义的多项式分布中抽取的num_samples个样本。
input每行的值不需要总和为1,但必须非负且总和不能为0.

当抽取样本时，依次从左到右排列(第一个样本对应第一列)。

如果输入input是一个向量，输出out也是一个相同长度num_samples的向量。如果输入input是有 m行的矩阵，输出out是形如m×n的矩阵。

如果参数replacement 为 True, 则样本抽取可以重复。否则，一个样本在每行不能被重复抽取。

参数num_samples必须小于input长度(即，input的列数，如果是input是一个矩阵)。

input(Tensor) - 包含概率值的张量
num_samples(int) - 抽取的样本数
replacement(bool, optional) - 布尔值，决定是否能重复抽取
out(Tensor, optional)
'''

'\ntorch.multinomial(input, num_samples, replacement=False, out=None):\n返回一个张量，每行包含从input相应行中定义的多项式分布中抽取的num_samples个样本。\ninput每行的值不需要总和为1,但必须非负且总和不能为0.\n\n当抽取样本时，依次从左到右排列(第一个样本对应第一列)。\n\n如果输入input是一个向量，输出out也是一个相同长度num_samples的向量。如果输入input是有 m行的矩阵，输出out是形如m×n的矩阵。\n\n如果参数replacement 为 True, 则样本抽取可以重复。否则，一个样本在每行不能被重复抽取。\n\n参数num_samples必须小于input长度(即，input的列数，如果是input是一个矩阵)。\n\ninput(Tensor) - 包含概率值的张量\nnum_samples(int) - 抽取的样本数\nreplacement(bool, optional) - 布尔值，决定是否能重复抽取\nout(Tensor, optional)\n'

In [67]:
torch.multinomial(x, 2)

tensor([[1, 0],
        [2, 1],
        [0, 1],
        [1, 0],
        [1, 2]])

In [68]:
'''
torch.normal(means, std, out=None):
返回一个张量，包含从给定means, std的离散正态分布中抽取随机数，均值和标准差的形状不须匹配，但每个张量的元素个数须相同

means(Tensor) - 均值
std(Tensor) - 标准差
out(Tensor, optional)
'''

'\ntorch.normal(means, std, out=None):\n返回一个张量，包含从给定means, std的离散正态分布中抽取随机数，均值和标准差的形状不须匹配，但每个张量的元素个数须相同\n\nmeans(Tensor) - 均值\nstd(Tensor) - 标准差\nout(Tensor, optional)\n'

In [69]:
torch.normal(mean=torch.arange(1., 11.), std=torch.arange(1, 0, -0.1))

tensor([ 1.2601,  2.0472,  3.7470,  4.3432,  4.8692,  6.0816,  7.6030,  8.1062,
         8.8146, 10.0819])

In [70]:
torch.normal(2, 3, size=(1, 4))

tensor([[4.6760, 1.9552, 2.4833, 4.4098]])

**5. 序列化 Serialization**

In [71]:
'''
torch.save(obj, f, pickle_module, pickle_protocol=2):
保存一个对象到一个硬盘文件上

obj - 保存对象
f - 类文件对象
pickle_module - 用于pickling元数据和对象的模块
pickle_protocol - 指定pickle protocal可以覆盖默认参数
'''

'\ntorch.save(obj, f, pickle_module, pickle_protocol=2):\n保存一个对象到一个硬盘文件上\n\nobj - 保存对象\nf - 类文件对象\npickle_module - 用于pickling元数据和对象的模块\npickle_protocol - 指定pickle protocal可以覆盖默认参数\n'

In [72]:
torch.save(x, 'tensor.pt')

In [73]:
'''
torch.load(f, map_location=None, pickle_module=):
从磁盘文件中读取一个通过torch.save()保存的对象，可通过参数map_location动态地进行内存重映射

f - 类文件对象
map_location - 一个函数或字典规定如何remap存储位置
pickle_module - 用于unpickling元数据和对象的模块
'''

'\ntorch.load(f, map_location=None, pickle_module=):\n从磁盘文件中读取一个通过torch.save()保存的对象，可通过参数map_location动态地进行内存重映射\n\nf - 类文件对象\nmap_location - 一个函数或字典规定如何remap存储位置\npickle_module - 用于unpickling元数据和对象的模块\n'

In [74]:
torch.load('tensor.pt')

tensor([[0.3023, 0.1208, 0.1272],
        [0.1766, 0.5085, 0.8517],
        [0.5513, 0.9506, 0.6067],
        [0.8191, 0.4089, 0.0038],
        [0.6152, 0.8712, 0.9641]])

**6. 并行化 Parallelism**

In [75]:
#获得用于并行化CPU操作的OpenMP线程数

torch.get_num_threads()

1

In [76]:
#设定用于并行化CPU操作的OpenMP线程数

torch.set_num_threads(1)

**7. 数学操作 Math operations**

**7.1 Pointwise Ops**

In [77]:
'''
torch.abs(input, out=None):
计算输入张量的每个元素绝对值

input(Tensor) - 输入张量
out(Tensor, optional) - 结果张量

torch.ceil(input, out=None):
对输入input张量每个元素向上取整，即取不小于每个元素的最小整数，并返回结果到输出

torch.exp(tensor, out=None):
返回一个新张量，包含输入input张量每个元素的指数

torch.floor(input, out=None):
返回一个新张量，包含输入input张量每个元素的floor，即不大于元素的最大整数。

torch.frac(tensor, out=None):
返回每个元素的分数部分

torch.log(input, out=None):
计算input的自然对数

torch.log1p(input, out=None):
计算input + 1的自然对数y = log(x + 1)
对值比较小的输入，此函数比torch.log()更准确

torch.neg(input, out=None):
返回一个新张量，包含输入input张量按元素取负。

torch.reciprocal(input, out=None):
返回一个新张量，包含输入input张量每个元素的倒数，即1.0/x

torch.round(input, out=None):
返回一个新张量，将输入input张量每个元素四舍五入到最近的整数。

torch.rsqrt(input, out=None):
返回一个新张量，包含输入input张量每个元素的平方根倒数。

torch.sigmoid(input, out=None):
返回一个新张量，包含输入input张量每个元素的sigmoid值
'''

'\ntorch.abs(input, out=None):\n计算输入张量的每个元素绝对值\n\ninput(Tensor) - 输入张量\nout(Tensor, optional) - 结果张量\n\ntorch.ceil(input, out=None):\n对输入input张量每个元素向上取整，即取不小于每个元素的最小整数，并返回结果到输出\n\ntorch.exp(tensor, out=None):\n返回一个新张量，包含输入input张量每个元素的指数\n\ntorch.floor(input, out=None):\n返回一个新张量，包含输入input张量每个元素的floor，即不大于元素的最大整数。\n\ntorch.frac(tensor, out=None):\n返回每个元素的分数部分\n\ntorch.log(input, out=None):\n计算input的自然对数\n\ntorch.log1p(input, out=None):\n计算input + 1的自然对数y = log(x + 1)\n对值比较小的输入，此函数比torch.log()更准确\n\ntorch.neg(input, out=None):\n返回一个新张量，包含输入input张量按元素取负。\n\ntorch.reciprocal(input, out=None):\n返回一个新张量，包含输入input张量每个元素的倒数，即1.0/x\n\ntorch.round(input, out=None):\n返回一个新张量，将输入input张量每个元素四舍五入到最近的整数。\n\ntorch.rsqrt(input, out=None):\n返回一个新张量，包含输入input张量每个元素的平方根倒数。\n\ntorch.sigmoid(input, out=None):\n返回一个新张量，包含输入input张量每个元素的sigmoid值\n'

In [78]:
torch.abs(torch.tensor([-1, -3, 5]))

tensor([1, 3, 5])

In [79]:
'''
torch.add(input, value, out=None):
对输入张量input逐元素加上标量值value，并返回结果到一个新的张量。

input(Tensor) - 输入张量
value(Number) - 添加到输入每个元素的数
out(Tensor, optional)

torch.div(input, value, out=None):
将input逐元素除以标量值value，并返回结果到输出张量out

torch.mul(input, value, out=None):
用标量值value乘以输入input的每个元素，并返回一个新的结果张量

torch.mul(input, other, out=None):
两个张量input, other按元素相乘，并返回到输出张量，两个张量形状不须匹配，但总元素数须一致。当形状不匹配时，input的形状作为输出张量的形状

torch.fmod(input, divisor, out=None):
计算除法余数，余数的正负与被除数相同

torch.remainder(input, divisor, out=None):
返回一个新张量，包含输入input张量每个元素的除法余数，余数与除数有相同的符号。
'''

'\ntorch.add(input, value, out=None):\n对输入张量input逐元素加上标量值value，并返回结果到一个新的张量。\n\ninput(Tensor) - 输入张量\nvalue(Number) - 添加到输入每个元素的数\nout(Tensor, optional)\n\ntorch.div(input, value, out=None):\n将input逐元素除以标量值value，并返回结果到输出张量out\n\ntorch.mul(input, value, out=None):\n用标量值value乘以输入input的每个元素，并返回一个新的结果张量\n\ntorch.mul(input, other, out=None):\n两个张量input, other按元素相乘，并返回到输出张量，两个张量形状不须匹配，但总元素数须一致。当形状不匹配时，input的形状作为输出张量的形状\n\ntorch.fmod(input, divisor, out=None):\n计算除法余数，余数的正负与被除数相同\n\ntorch.remainder(input, divisor, out=None):\n返回一个新张量，包含输入input张量每个元素的除法余数，余数与除数有相同的符号。\n'

In [80]:
torch.remainder(torch.tensor([-3., -2, -1, 1, 2, 3]), 2)

tensor([1., 0., 1., 1., 0., 1.])

In [81]:
'''
torch.addcdiv(tensor, value=1, tensor1, tensor2, out=None):
用tensor2对tensor1逐元素相除，然后乘以标量值value并加到tensor上。

tensor(Tensor) - 张量
value(Number, optional) - 标量
tensor1(Tensor) - 张量，作为分子
tensor2(Tensor) - 张量，作为分母
out(Tensor, optional)

torch.addcmul(tensor, value=1, tensor1, tensor2, out=None):
用tensor2对tensor1逐元素相乘，并对结果乘以标量值value然后加到tensor，张量形状不需要匹配，但元素数量必须一致。

'''

'\ntorch.addcdiv(tensor, value=1, tensor1, tensor2, out=None):\n用tensor2对tensor1逐元素相除，然后乘以标量值value并加到tensor上。\n\ntensor(Tensor) - 张量\nvalue(Number, optional) - 标量\ntensor1(Tensor) - 张量，作为分子\ntensor2(Tensor) - 张量，作为分母\nout(Tensor, optional)\n\ntorch.addcmul(tensor, value=1, tensor1, tensor2, out=None):\n用tensor2对tensor1逐元素相乘，并对结果乘以标量值value然后加到tensor，张量形状不需要匹配，但元素数量必须一致。\n\n'

In [82]:
t = torch.rand(3,3)
t1 = torch.rand(3,1)
t2 = torch.rand(1,3)
torch.addcdiv(t, 0.1, t1, t2)

tensor([[0.3190, 0.1743, 0.1156],
        [0.5876, 0.2322, 0.8217],
        [0.8436, 0.7516, 0.9999]])

In [83]:
'''
torch.clamp(input, min, max, out=None):
将输入input张量每个元素值约束到区间[min, max]，并返回结果到一个新张量
也可以只设定min或只设定max

input(Tensor) - 输入张量
min(Number) - 限制范围下限
max(Number) - 限制范围上限
out(Tensor, optional)
'''

'\ntorch.clamp(input, min, max, out=None):\n将输入input张量每个元素值约束到区间[min, max]，并返回结果到一个新张量\n也可以只设定min或只设定max\n\ninput(Tensor) - 输入张量\nmin(Number) - 限制范围下限\nmax(Number) - 限制范围上限\nout(Tensor, optional)\n'

In [84]:
torch.clamp(x, 0.4, 0.6)

tensor([[0.4000, 0.4000, 0.4000],
        [0.4000, 0.5085, 0.6000],
        [0.5513, 0.6000, 0.6000],
        [0.6000, 0.4089, 0.4000],
        [0.6000, 0.6000, 0.6000]])

In [85]:
'''
torch.lerp(start, end, weight, out=None):
对两个张量以start, end做线性插值，将结果返回到输出张量
out = start + weight*(end - start)

start(Tensor) - 起始点张量
end(Tensor) - 终止点张量
weight(float) - 插值公式中的weight
out(Tensor, optional)
'''

'\ntorch.lerp(start, end, weight, out=None):\n对两个张量以start, end做线性插值，将结果返回到输出张量\nout = start + weight*(end - start)\n\nstart(Tensor) - 起始点张量\nend(Tensor) - 终止点张量\nweight(float) - 插值公式中的weight\nout(Tensor, optional)\n'

In [86]:
start = torch.arange(1., 5.)
end = torch.empty(4).fill_(10)
torch.lerp(start, end, 0.5)

tensor([5.5000, 6.0000, 6.5000, 7.0000])

In [87]:
'''
torch.pow(input, exponent, out=None):
对输入input按元素求exponent次幂，并返回结果张量。幂可以为float数或与input相同元素数的张量

torch.pow(base, input, out=None):
base为标量浮点值，input为张量。

base(float) - 标量值，指数的底
input(Tensor) - 幂值
out(Tensor, optional)
'''

'\ntorch.pow(input, exponent, out=None):\n对输入input按元素求exponent次幂，并返回结果张量。幂可以为float数或与input相同元素数的张量\n\ntorch.pow(base, input, out=None):\nbase为标量浮点值，input为张量。\n\nbase(float) - 标量值，指数的底\ninput(Tensor) - 幂值\nout(Tensor, optional)\n'

In [88]:
torch.pow(2, torch.arange(1,5))

tensor([ 2,  4,  8, 16])

**7.2 Reduction Ops**

In [89]:
'''
torch.dist(input, other, p=2, out=None) -> Tensor:
返回(input - other)的p范数

input(Tensor) - 输入张量
other(Tensor) - 右侧输入张量
p(float, optional) - 要计算的范数
out(Tensor, optional)
'''

'\ntorch.dist(input, other, p=2, out=None) -> Tensor:\n返回(input - other)的p范数\n\ninput(Tensor) - 输入张量\nother(Tensor) - 右侧输入张量\np(float, optional) - 要计算的范数\nout(Tensor, optional)\n'

In [90]:
a = torch.randn(4)
b = torch.randn(4)
torch.dist(a, b, 1)

tensor(2.6435)

In [91]:
'''
torch.cumsum(input, dim, out=None) -> Tensor:
返回输入沿指定维度的累积和
'''

'\ntorch.cumsum(input, dim, out=None) -> Tensor:\n返回输入沿指定维度的累积和\n'

In [92]:
torch.cumsum(torch.randn(2), dim = 0)

tensor([-0.7289, -1.1486])

In [93]:
'''
torch.dist(input, other, p=2, out=None) -> Tensor:
返回(input - other)的p范数

input(Tensor) - 输入张量
other(Tensor) - 右侧输入张量
p(float, optional) - 要计算的范数
out(Tensor, optional)
'''

'\ntorch.dist(input, other, p=2, out=None) -> Tensor:\n返回(input - other)的p范数\n\ninput(Tensor) - 输入张量\nother(Tensor) - 右侧输入张量\np(float, optional) - 要计算的范数\nout(Tensor, optional)\n'

In [94]:
torch.dist(torch.randn(4), torch.randn(4),2)

tensor(3.2532)

In [95]:
'''
torch.norm(input, p=2) -> float:
返回输入张量input的p范数。

input(Tensor) - 输入张量
p(float, optional) - 范数计算中的幂指数值

torch.norm(input, p, dim, out=None) -> Tensor:
返回输入张量给定维度dim上每行的p范数。
'''

'\ntorch.norm(input, p=2) -> float:\n返回输入张量input的p范数。\n\ninput(Tensor) - 输入张量\np(float, optional) - 范数计算中的幂指数值\n\ntorch.norm(input, p, dim, out=None) -> Tensor:\n返回输入张量给定维度dim上每行的p范数。\n'

In [96]:
torch.norm(torch.randn(5,2), 1, dim = 0)

tensor([1.8089, 1.6202])

In [97]:
'''
torch.prod(input) -> float:
返回输入张量input所有元素的积

torch.prod(input, dim, out=None) -> Tensor:
返回输入张量给定维度上每行的积。

torch.std(input) -> float:
返回输入张量input所有元素的标准差

torch.std(input, dim, out=None):
返回输入张量给定维度上每行的标准差。

torch.sum(input) -> float:
返回输入张量input所有元素的各

torch.sum(input, dim, out=None) -> Tensor:
返回输入疑是给定维度上每行的和

torch.var(input) -> float:
返回输入张量所有元素的方差

torch.var(input, dim, out=None) -> Tensor:
返回输入张量给定维度上每行的方差。
'''

'\ntorch.prod(input) -> float:\n返回输入张量input所有元素的积\n\ntorch.prod(input, dim, out=None) -> Tensor:\n返回输入张量给定维度上每行的积。\n\ntorch.std(input) -> float:\n返回输入张量input所有元素的标准差\n\ntorch.std(input, dim, out=None):\n返回输入张量给定维度上每行的标准差。\n\ntorch.sum(input) -> float:\n返回输入张量input所有元素的各\n\ntorch.sum(input, dim, out=None) -> Tensor:\n返回输入疑是给定维度上每行的和\n\ntorch.var(input) -> float:\n返回输入张量所有元素的方差\n\ntorch.var(input, dim, out=None) -> Tensor:\n返回输入张量给定维度上每行的方差。\n'

In [98]:
torch.prod(torch.arange(1., 4.))

tensor(6.)

**7.3 比较操作Comparison Ops**

In [99]:
'''
torch.eq(input, other, out=None) -> Tensor:
比较元素相等性，第二个参数可为一个数，或与第一个参数同类型形状的张量

input(Tensor) - 待比较张量
other(Tensor or float) - 比较张量或数
out(Tensor, optional) - 输出张量，须为ByteTensor类型或与input同类型
'''

'\ntorch.eq(input, other, out=None) -> Tensor:\n比较元素相等性，第二个参数可为一个数，或与第一个参数同类型形状的张量\n\ninput(Tensor) - 待比较张量\nother(Tensor or float) - 比较张量或数\nout(Tensor, optional) - 输出张量，须为ByteTensor类型或与input同类型\n'

In [100]:
torch.eq(torch.tensor([[1, 2], [3, 4]]), torch.tensor([[1, 1], [4, 4]]))

tensor([[ True, False],
        [False,  True]])

In [101]:
#若两个张量有相同的形状和元素值，则返回True， 否则False。

torch.equal(torch.tensor([[1, 2], [3, 4]]),torch.tensor([[1, 2], [3, 4]]))

True

In [102]:
'''
torch.ge(input, other, out=None) -> Tensor:
逐元素比较input和other，即是否input >= other
第二个参数可以为一个数或与第一个参数相同形状和类型的张量。

input(Tensor) - 待对比的张量
other(Tensor or float) - 对比的张量或float值
out(Tensor, optional) - 输出张量，必须为ByteTensor或与第一个参数相同类型。
'''

'\ntorch.ge(input, other, out=None) -> Tensor:\n逐元素比较input和other，即是否input >= other\n第二个参数可以为一个数或与第一个参数相同形状和类型的张量。\n\ninput(Tensor) - 待对比的张量\nother(Tensor or float) - 对比的张量或float值\nout(Tensor, optional) - 输出张量，必须为ByteTensor或与第一个参数相同类型。\n'

In [103]:
torch.ge(torch.tensor([[1, 2], [3, 4]]), torch.tensor([[1, 1], [4, 4]]))

tensor([[ True,  True],
        [False,  True]])

In [104]:
'''
torch.gt(input, other, out=None) -> Tensor:
逐元素比较input和other，是否input > other。若两个张量有相同的形状和元素值，则返回True，否则False。第二个参数
可以为一个数或与第一个参数相同形状和类型的张量。
'''

'\ntorch.gt(input, other, out=None) -> Tensor:\n逐元素比较input和other，是否input > other。若两个张量有相同的形状和元素值，则返回True，否则False。第二个参数\n可以为一个数或与第一个参数相同形状和类型的张量。\n'

In [105]:
torch.gt(torch.tensor([[1, 2], [3, 4]]), torch.tensor([[1, 1], [4, 4]]))

tensor([[False,  True],
        [False, False]])

In [106]:
'''
torch.kthvalue(input, k, dim=None, out=None) -> (Tensor, LongTensor):
取输入张量input指定维度上第k个最小值，若不指定dim，则默认为input的最后一维。返回一个元组，其中indices是原始输入张量input中沿dim维的第k个最小值下标。

input(Tensor) - 输入张量
k(int) - 第k个最小值
dim(int, optional)` - 沿着此维度进行排序
out(tuple, optional) - 输出元组
'''

'\ntorch.kthvalue(input, k, dim=None, out=None) -> (Tensor, LongTensor):\n取输入张量input指定维度上第k个最小值，若不指定dim，则默认为input的最后一维。返回一个元组，其中indices是原始输入张量input中沿dim维的第k个最小值下标。\n\ninput(Tensor) - 输入张量\nk(int) - 第k个最小值\ndim(int, optional)` - 沿着此维度进行排序\nout(tuple, optional) - 输出元组\n'

In [107]:
x = torch.rand(4,2)
torch.kthvalue(x, 1, dim = 0)

torch.return_types.kthvalue(
values=tensor([0.0182, 0.4338]),
indices=tensor([3, 2]))

In [108]:
'''
torch.le(input, other, out=None) -> Tensor:
逐元素比较input和other，即是否input <= other，第二个参数可以为一个数或与第一个参数相同形状和类型的张量。

torch.lt(input, other, out=None) -> Tensor:
逐元素比较input和other，即是否input < other

torch.ne(input, other, out=Tensor) -> Tensor:
逐元素比较input和other， 即是否input != other。第二个参数可以为一个数或与第一个参数相同形状和类型的张量。
返回值：一个torch.ByteTensor张量，包含了每个位置的比较结果(如果tensor != other 为True，返回1)。

'''

'\ntorch.le(input, other, out=None) -> Tensor:\n逐元素比较input和other，即是否input <= other，第二个参数可以为一个数或与第一个参数相同形状和类型的张量。\n\ntorch.lt(input, other, out=None) -> Tensor:\n逐元素比较input和other，即是否input < other\n\ntorch.ne(input, other, out=Tensor) -> Tensor:\n逐元素比较input和other， 即是否input != other。第二个参数可以为一个数或与第一个参数相同形状和类型的张量。\n返回值：一个torch.ByteTensor张量，包含了每个位置的比较结果(如果tensor != other 为True，返回1)。\n\n'

In [109]:
torch.le(torch.tensor([[1, 2], [3, 4]]), 3)

tensor([[ True,  True],
        [ True, False]])

In [110]:
'''
torch.max(input, dim, max=None, max_indice=None) -> (Tensor, LongTensor):
返回输入张量给定维度上每行的最大值，并同时返回每个最大值的位置索引。

input(Tensor) - 输入张量
dim(int) - 指定的维度
max(Tensor, optional) - 结果张量，包含给定维度上的最大值
max_indices(LongTensor, optional) - 包含给定维度上每个最大值的位置索引。

torch.min(input, dim, min=None, min_indices=None) -> (Tensor, LongTensor):
返回输入张量给定维度上每行的最小值，并同时返回每个最小值的位置索引。

torch.min(input, other, out=None) -> Tensor:
input中逐元素与other相应位置的元素对比，返回最小值到输出张量。
两张量形状不需匹配，但元素数须相同。
'''

'\ntorch.max(input, dim, max=None, max_indice=None) -> (Tensor, LongTensor):\n返回输入张量给定维度上每行的最大值，并同时返回每个最大值的位置索引。\n\ninput(Tensor) - 输入张量\ndim(int) - 指定的维度\nmax(Tensor, optional) - 结果张量，包含给定维度上的最大值\nmax_indices(LongTensor, optional) - 包含给定维度上每个最大值的位置索引。\n\ntorch.min(input, dim, min=None, min_indices=None) -> (Tensor, LongTensor):\n返回输入张量给定维度上每行的最小值，并同时返回每个最小值的位置索引。\n\ntorch.min(input, other, out=None) -> Tensor:\ninput中逐元素与other相应位置的元素对比，返回最小值到输出张量。\n两张量形状不需匹配，但元素数须相同。\n'

In [111]:
torch.max(torch.randn(4, 4), 1)

torch.return_types.max(
values=tensor([1.4699, 1.2911, 0.9563, 0.0776]),
indices=tensor([1, 0, 0, 1]))

In [112]:
'''
torch.sort(input, dim=None, descending=False, out=None) -> (Tensor, LongTensor):
对输入张量input沿着指定维度按升序排序，如果不给定dim，默认为输入的最后一维。如果指定参数descending为True，则按降序排序。
返回两项：重排后的张量，和重排后元素在原张量的索引

input(Tensor) - 输入张量
dim(int, optional) - 沿此维排序，默认为最后一维
descending(bool, optional) - 布尔值，默认升序

'''

'\ntorch.sort(input, dim=None, descending=False, out=None) -> (Tensor, LongTensor):\n对输入张量input沿着指定维度按升序排序，如果不给定dim，默认为输入的最后一维。如果指定参数descending为True，则按降序排序。\n返回两项：重排后的张量，和重排后元素在原张量的索引\n\ninput(Tensor) - 输入张量\ndim(int, optional) - 沿此维排序，默认为最后一维\ndescending(bool, optional) - 布尔值，默认升序\n\n'

In [113]:
torch.sort(torch.randn(3, 2))

torch.return_types.sort(
values=tensor([[ 0.1528,  1.7705],
        [ 0.9364,  1.0923],
        [-1.3573,  1.9534]]),
indices=tensor([[1, 0],
        [1, 0],
        [1, 0]]))

In [114]:
'''
torch.topk(input, k, dim=None, largest=True, sorted=True, out=None) -> (Tensor, LongTensor):
沿给定dim维度返回输入张量input中k个最大值，不指定dim，则默认为最后一维，如果largest为False，则返回最小的k个值。
'''

'\ntorch.topk(input, k, dim=None, largest=True, sorted=True, out=None) -> (Tensor, LongTensor):\n沿给定dim维度返回输入张量input中k个最大值，不指定dim，则默认为最后一维，如果largest为False，则返回最小的k个值。\n'

In [115]:
torch.topk(torch.arange(1., 6.), 2)

torch.return_types.topk(
values=tensor([5., 4.]),
indices=tensor([4, 3]))

**7.4 其它操作 Other Operations**

In [116]:
'''
torch.cross(input, other, dim=-1, out=None) -> Tensor:
返回沿着维度dim上，两个张量input和other的叉积。input和other必须有相同的形状，且指定的dim维上size必须为3。如果不指定dim，则默认为第一个尺度为3的维。
'''

'\ntorch.cross(input, other, dim=-1, out=None) -> Tensor:\n返回沿着维度dim上，两个张量input和other的叉积。input和other必须有相同的形状，且指定的dim维上size必须为3。如果不指定dim，则默认为第一个尺度为3的维。\n'

In [117]:
a = torch.rand(4, 3)
b = torch.rand(4, 3)
torch.cross(a, b, dim = 1)

tensor([[ 0.3005, -0.2538, -0.0702],
        [-0.0242, -0.1374,  0.1270],
        [ 0.4252, -0.2002,  0.0841],
        [ 0.3947, -0.0545, -0.0835]])

In [118]:
'''
torch.diag(input, diagonal=0, out=None) -> Tensor:
如果输入是一个向量，则返回一个以input为对角线元素的2D方阵
如果输入是一个矩阵，则返回一个包含input为对角元素的1D张量
参数diagonal指定对角线：

diagonal = 0, 主对角线
diagonal > 0, 主对角线之上
diagonal < 0, 主对角线之下
'''

'\ntorch.diag(input, diagonal=0, out=None) -> Tensor:\n如果输入是一个向量，则返回一个以input为对角线元素的2D方阵\n如果输入是一个矩阵，则返回一个包含input为对角元素的1D张量\n参数diagonal指定对角线：\n\ndiagonal = 0, 主对角线\ndiagonal > 0, 主对角线之上\ndiagonal < 0, 主对角线之下\n'

In [119]:
torch.diag(a, 0)

tensor([0.5010, 0.5550, 0.8334])

**7.5 BLAS and LAPACK Operations**

In [120]:
#计算两个张量的点乘，两个张量都为1-D向量

torch.dot(torch.tensor([2, 3]), torch.tensor([2, 1]))

tensor(7)

In [121]:
'''
torch.eig(a, eigenvectors=False, out=None) -> (Tensor, Tensor):
计算方阵a的特征值和特征向量。

a(Tensor) - 方阵
eigenvectors(bool) - 如果为True，同时计算特征值和特征微量，否则只计算特征值
返回值：
e(Tensor) - a的右特征向量
v(Tensor) - 如果eigenvectors为True，则为包含特征向量的张量，否则为空。
'''

'\ntorch.eig(a, eigenvectors=False, out=None) -> (Tensor, Tensor):\n计算方阵a的特征值和特征向量。\n\na(Tensor) - 方阵\neigenvectors(bool) - 如果为True，同时计算特征值和特征微量，否则只计算特征值\n返回值：\ne(Tensor) - a的右特征向量\nv(Tensor) - 如果eigenvectors为True，则为包含特征向量的张量，否则为空。\n'

In [122]:
a = torch.randn(4, 4)
torch.eig(a, eigenvectors=True)

torch.return_types.eig(
eigenvalues=tensor([[-0.5800,  0.0000],
        [ 0.4666,  1.2305],
        [ 0.4666, -1.2305],
        [ 2.9537,  0.0000]]),
eigenvectors=tensor([[ 0.6441, -0.1876, -0.4172,  0.1589],
        [-0.3511, -0.1679, -0.1145,  0.5574],
        [ 0.3840,  0.7927,  0.0000,  0.1068],
        [ 0.5607,  0.2618,  0.2293,  0.8079]]))

In [123]:
#对方阵input求逆
torch.inverse(a)

tensor([[-0.6081,  1.0322, -0.1980, -0.4998],
        [ 0.3066, -0.6002, -0.4268,  0.6438],
        [ 0.2513,  1.5589,  1.0621, -1.2205],
        [-0.5015,  1.5097,  0.7268, -0.7004]])

In [124]:
#对矩阵mat1和mat2进行相乘。
x = torch.rand(2, 3)
y = torch.rand(3, 5)
torch.mm(x, y)

tensor([[0.4574, 0.8024, 1.0718, 0.3288, 0.5557],
        [0.4101, 0.4200, 0.6404, 0.6583, 0.2505]])

In [125]:
#对矩阵mat和向量vec进行相乘。
v = torch.rand(3)
torch.mv(x, v)

tensor([1.2337, 0.8232])