In [2]:
"""
https://www.jianshu.com/p/d678c5e44a6b
torch常用基础函数    
"""
import torch
import torch.nn.functional as F     # 激励函数都在这
from torch.autograd import Variable
import numpy as np
# python 的可视化模块, 我有教程 (https://morvanzhou.github.io/tutorials/data-manipulation/plt/)
import matplotlib.pyplot as plt
%matplotlib inline

#### 1.张量Tensors

In [3]:
x = torch.rand(5, 3)
x

tensor([[0.7981, 0.7250, 0.4451],
        [0.6877, 0.1505, 0.6644],
        [0.7982, 0.9118, 0.1653],
        [0.2729, 0.6268, 0.4802],
        [0.0194, 0.8225, 0.1178]])

In [5]:
# 如果obj是一个pytorch张量，则返回True
torch.is_tensor(x)

True

In [6]:
# 如果obj是一个pytorch storage对象，则返回True
torch.is_storage(x)

False

In [7]:
# 返回input张量中的元素个数
torch.numel(x)

15

#### 2. 创建操作

In [11]:
"""
torch.eye(n, m=None, out=None):
返回一个2维张量，对角线为1,其它位置为0

n (int) -行数
m (int, optional)列数，如果为None,则默认为n
out (Tensor, optional)
"""
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [18]:
nda = np.array([[1,  2],  [3,  4]])  
print(type(nda))
nda

<class 'numpy.ndarray'>


array([[1, 2],
       [3, 4]])

In [21]:
nda_tr = torch.from_numpy(nda)
nda_tr

tensor([[1, 2],
        [3, 4]])

In [20]:
"""
将numpy.ndarray转换为Tensor，返回的张量tensor和numpy的ndarray共享同一内存空间，
修改一个会导致另一个也被修改，返回的张量不能改变大小
"""

'\n将numpy.ndarray转换为Tensor，返回的张量tensor和numpy的ndarray共享同一内存空间，\n修改一个会导致另一个也被修改，返回的张量不能改变大小\n'

In [27]:
nda[0,1]=9
nda

array([[1, 9],
       [3, 4]])

In [28]:
nda_tr

tensor([[1, 9],
        [3, 4]])

In [29]:
"""
torch.linspace(start, end, steps=100, out=None):
返回一个1维张量，包含在start和end上均匀间隔的steps个点

start (float) -序列起点
end (float) - 序列终点
steps (int) - 在start与end间生成的样本数
out (Tensor, optional) - 结果张量
"""

'\ntorch.linspace(start, end, steps=100, out=None):\n返回一个1维张量，包含在start和end上均匀间隔的steps个点\n\nstart (float) -序列起点\nend (float) - 序列终点\nsteps (int) - 在start与end间生成的样本数\nout (Tensor, optional) - 结果张量\n'

In [30]:
torch.linspace(1, 100, steps=10, out=None)

tensor([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [31]:
"""
torch.logspace(start, end, steps=100, out=None):
返回一个1维张量，包含在区间10exp(start)和10exp(end)上以对数刻度均匀间隔的 steps个点。
"""

'\ntorch.logspace(start, end, steps=100, out=None):\n返回一个1维张量，包含在区间10exp(start)和10exp(end)上以对数刻度均匀间隔的 steps个点。\n'